<template>
  <a-breadcrumb class="container-breadcrumb">
    <a-breadcrumb-item>
      <router-link to="/">
        <icon-apps />
      </router-link>
    </a-breadcrumb-item>
    <a-breadcrumb-item v-for="(item, index) in itemsSource" :key="getItemKey(item, index)">
      <router-link v-if="getItemPath(item, index)" :to="getItemPath(item, index)">{{ $t(getItemLocale(item)) }}</router-link>
      <span v-else>{{ $t(getItemLocale(item)) }}</span>
    </a-breadcrumb-item>
  </a-breadcrumb>
</template>

<script lang="ts" setup>
import { IconHome } from '@arco-design/web-vue/es/icon'
import { PropType, computed } from 'vue'
import { useRoute } from 'vue-router'

interface BreadcrumbItem {
  locale: string
  path: string
}

const props = defineProps({
  items: {
    type: Array as PropType<BreadcrumbItem[] | string[]>,
    default() {
      return []
    },
  },
})

// Generate path from locale (simplified - may need adjustment based on routing)
const generatePathFromLocale = (locale: string): string => {
  // This is a simple mapping - you might need to adjust based on your routing structure
  const pathMap: Record<string, string> = {
    'menu.dashboard': '/dashboard',
    'menu.dashboard.monitor': '/dashboard/monitor',
    'menu.visualization': '/visualization',
    'menu.visualization.multiDimensionDataAnalysis': '/visualization/multi-dimension-data-analysis',
    'menu.visualization.dataAnalysis': '/visualization/data-analysis',
    'menu.user': '/user',
    'menu.user.setting': '/user/setting',
    'menu.user.info': '/user/info',
    'menu.result': '/result',
    'menu.result.success': '/result/success',
    'menu.result.error': '/result/error',
    'menu.profile': '/profile',
    'menu.profile.basic': '/profile/basic',
    'menu.list': '/list',
    'menu.list.searchTable': '/list/search-table',
    'menu.list.cardList': '/list/card',
    'menu.form': '/form',
    'menu.form.step': '/form/step',
    'menu.form.group': '/form/group',
    'menu.exception': '/exception',
    'menu.exception.500': '/exception/500',
    'menu.exception.404': '/exception/404',
    'menu.exception.403': '/exception/403',
    'menu.quan-ly-san-pham': '/quan-ly-san-pham',
    'menu.quan-ly-san-pham.danh-muc': '/quan-ly-san-pham/danh-muc',
    'menu.quan-ly-san-pham.them-san-pham': '/quan-ly-san-pham/them-san-pham',
    'menu.quan-ly-san-pham.bien-the': '/quan-ly-san-pham/bien-the',
    'menu.ban-hang-tai-quay': '/ban-hang-tai-quay',
    'menu.quan-ly-san-pham.thuoc-tinh': '/quan-ly-san-pham/thuoc-tinh',
    'menu.quan-ly-san-pham.thuoc-tinh.anh-san-pham': '/quan-ly-san-pham/thuoc-tinh/anh-san-pham',
    'menu.quan-ly-san-pham.thuoc-tinh.nha-san-xuat': '/quan-ly-san-pham/thuoc-tinh/nha-san-xuat',
    'menu.quan-ly-san-pham.thuoc-tinh.xuat-xu': '/quan-ly-san-pham/thuoc-tinh/xuat-xu',
    'menu.quan-ly-san-pham.thuoc-tinh.mau-sac': '/quan-ly-san-pham/thuoc-tinh/mau-sac',
    'menu.quan-ly-san-pham.thuoc-tinh.kich-thuoc': '/quan-ly-san-pham/thuoc-tinh/kich-thuoc',
    'menu.quan-ly-san-pham.thuoc-tinh.de-giay': '/quan-ly-san-pham/thuoc-tinh/de-giay',
    'menu.quan-ly-san-pham.thuoc-tinh.chat-lieu': '/quan-ly-san-pham/thuoc-tinh/chat-lieu',
    'menu.quan-ly-san-pham.thuoc-tinh.trong-luong': '/quan-ly-san-pham/thuoc-tinh/trong-luong',
  }
  return pathMap[locale] || ''
}

const route = useRoute()

// Process items to handle both formats: string[] and BreadcrumbItem[]
const processedItems = computed(() => {
  return props.items.map((item) => {
    if (typeof item === 'string') {
      // Convert string to BreadcrumbItem format
      return {
        locale: item,
        path: '', // Path will be generated dynamically in getItemPath
      }
    }
    return item
  })
})

// Auto-generate from current route when no items passed
const autoGenerated = computed(() => {
  if (props.items && (props.items as any[]).length > 0) return []
  const matched = route.matched.filter((m) => m.meta && (m.meta as any).locale)
  let accPath = ''
  const items = matched.map((m, idx) => {
    // Build path cumulatively for parent navigation
    accPath = m.path.startsWith('/') ? m.path : `${accPath}/${m.path}`
    return {
      locale: String(m.meta?.locale || m.name || m.path),
      path: idx === matched.length - 1 ? '' : accPath,
    } as BreadcrumbItem
  })
  
  // Filter out duplicate consecutive locales
  return items.filter((item, idx) => {
    if (idx === 0) return true
    return item.locale !== items[idx - 1].locale
  })
})

const itemsSource = computed(() => (processedItems.value.length ? processedItems.value : autoGenerated.value))

// Helper functions to get properties regardless of format
const getItemLocale = (item: BreadcrumbItem | string): string => {
  if (typeof item === 'string') {
    return item
  }
  return item.locale || ''
}

const getItemPath = (item: BreadcrumbItem | string, index: number): string => {
  const total = itemsSource.value.length
  const isLastItem = index === total - 1
  if (isLastItem) return '' // Current page, no link

  return typeof item === 'string' ? generatePathFromLocale(item) : item.path
}

const getItemKey = (item: BreadcrumbItem | string, index: number): string => {
  return typeof item === 'string' ? `${item}-${index}` : item.locale
}
</script>

<style scoped lang="less">
.container-breadcrumb {
  margin: 16px 0;
  :deep(.arco-breadcrumb-item) {
    color: rgb(var(--gray-6));
    &:last-child {
      color: rgb(var(--gray-8));
    }
  }
}
</style>
